version: '3.8'

services:
  app:
    image: 360smartconnect/gs1_decoder_api:lastest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.services.http-0-tos8ck0k4kw44o80sg8s0g84.loadbalancer.server.port="8000"