# docker-compose.yaml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 360smartconnect/gs1_decoder_api:latest
    expose:
      - 8000
    # Monte un volume pour récupérer tes logs de debug
    volumes:
      - ./logs:/tmp/logs
    labels:
      - traefik.enable=true
      - "traefik.http.routers.gs1-api.rule=Host(`gs1-decoder-api.rorworld.eu`)"
      - "traefik.http.routers.gs1-api.entryPoints=http"
    # Optionnel : redirige le port interne vers l'extérieur (si besoin en dev)
    ports:
      - "8000:8000"
